/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { promisify } from 'node:util';
import { exec as execCb } from 'node:child_process';
import { copyFile, mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const exec = promisify(execCb);

export interface ProposeResult {
  success: boolean;
  prUrl?: string;
  message: string;
}

const UPSTREAM = 'google-gemini/gemini-cli';

export async function proposeEvalUpstream(
  evalPath: string,
  evalName: string,
): Promise<ProposeResult> {
  // Check gh is available
  try {
    await exec('gh --version');
  } catch {
    return {
      success: false,
      message:
        'gh CLI not found. Install from cli.github.com then run: gh auth login',
    };
  }

  // Check gh is authenticated
  try {
    await exec('gh auth status');
  } catch {
    return {
      success: false,
      message: 'Not logged into gh. Run: gh auth login',
    };
  }

  // Get username
  let username: string;
  try {
    const { stdout } = await exec('gh api user -q .login');
    username = stdout.trim();
  } catch {
    return { success: false, message: 'Could not get GitHub username.' };
  }

  // Fork upstream (idempotent)
  try {
    await exec(`gh repo fork ${UPSTREAM} --clone=false`);
  } catch {
    /* already forked — continue */
  }

  const branchName = `eval/${evalName}`;
  const prTitle = `feat(evals): add ${evalName} behavioral eval`;
  const prBody = [
    '## Summary',
    '',
    `Adds the \`${evalName}\` behavioral eval, auto-generated by Gemini CLI.`,
    '',
    '## Test plan',
    '- [ ] Run `npm run test:all_evals` and confirm the eval passes at ≥66%',
    '- [ ] Review assertion logic and prompt for correctness',
    '- [ ] Confirm rule text uses positive framing',
  ].join('\n');

  let tmpDir: string | null = null;

  try {
    // Shallow-clone the fork into a temp dir
    tmpDir = await mkdtemp(join(tmpdir(), 'gemini-eval-'));
    await exec(
      `gh repo clone ${username}/gemini-cli "${tmpDir}" -- --depth 1 --quiet`,
    );

    // Create branch
    await exec(`git -C "${tmpDir}" checkout -b ${branchName}`);

    // Copy the eval file into evals/
    await copyFile(evalPath, join(tmpDir, 'evals', `${evalName}.eval.ts`));

    // Commit (use neutral identity in case local git has no user config)
    await exec(`git -C "${tmpDir}" add evals/${evalName}.eval.ts`);
    await exec(
      `git -C "${tmpDir}" -c user.name="Gemini CLI" -c user.email="gemini-cli@users.noreply.github.com" ` +
        `commit -m "${prTitle}"`,
    );

    // Push branch to fork
    await exec(`git -C "${tmpDir}" push origin ${branchName}`);

    // Open PR from fork branch → upstream main
    const { stdout: prOut } = await exec(
      `gh pr create --repo ${UPSTREAM} ` +
        `--head "${username}:${branchName}" ` +
        `--base main ` +
        `--title "${prTitle}" ` +
        `--body "${prBody.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`,
      { cwd: tmpDir },
    );

    const prUrl = prOut.trim().split('\n').pop() ?? '';

    // Open PR in browser
    const openCmd =
      process.platform === 'win32'
        ? `start "" "${prUrl}"`
        : process.platform === 'darwin'
          ? `open "${prUrl}"`
          : `xdg-open "${prUrl}"`;
    await exec(openCmd).catch(() => {});

    return { success: true, prUrl, message: `PR opened: ${prUrl}` };
  } catch (err) {
    const raw = err instanceof Error ? err.message : String(err);
    // Pull out the most useful line from gh/git error output
    const useful =
      raw
        .split('\n')
        .find((l) => l.trim().length > 0 && !l.startsWith('To ')) ?? raw;
    return { success: false, message: useful.slice(0, 120) };
  } finally {
    if (tmpDir)
      await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }
}
